server:
  port: 8080

spring:
  application:
    name: bms-control-system
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

mqtt:
  broker:
    host: localhost
    port: 8010
    username:
    password:
  topics:
    bms-status: bms/status
    bms-control: bms/control
    bms-cell-voltage: bms/cell/voltage
    bms-temperature: bms/temperature
    bms-current: bms/current
    bms-capacity: bms/capacity
    bms-fet-status: bms/fet/status
    electronic-load-control: electronic_load/control

logging:
  level:
    com.bms: INFO
    org.springframework.integration.mqtt.outbound: DEBUG
    org.springframework.integration.mqtt.inbound: WARN
    org.springframework.integration.channel: WARN
    org.springframework.integration.handler: WARN
